app = "punch-out-ai"  # Your Fly app name

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  # Set the build context to the python folder so the buildpack sees your code and dependencies.
  context = "./python"
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/python"]

[env]
  PORT = "8000"  # Fly.io sets this for your app

# Use an entrypoint that runs your FastAPI app.
entrypoint = "uvicorn api:app --reload --host 0.0.0.0 --port $PORT"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

